
clear
sequence='ATGCCCCGGAATGCACCCCGACTTCGATTGCAGTCATGCAATGCAGATTTAAACCGATGGTAGCGTGCATGCCTGCTAGCATGCATGCCACAGTAGCAGTAGATATATATGGGACACACGTATATGCACACAC'
err_pro=0.01;
err_type=1;
new_sequence = err_fun(sequence,err_type,err_pro)